# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- id: go_test #testa a aplicação
  name: "gcr.io/cloud-builders/go"
  args: ["test","webserver"]
  env: ["GOPATH=go/."]

- name: 'gcr.io/cloud-builders/docker' #Gera uma imagem a partir do projeto
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.24.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/golang-webserver:latest'
  - 'go/.'

- name: 'gcr.io/cloud-builders/go' #mostra a versão do Go
  args: ['version']
  env: ['GOPATH=go/.']



- name: 'gcr.io/cloud-builders/go' #Executa a soma.
  args: ['run', 'webserver']
  env: ['GOPATH=go/.']

images:
- 'gcr.io/$PROJECT_ID/golang-webserver:latest' #
