apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: gowebserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gowebserver
    spec:
      containers:
      - name: gowebserver
        image: allanlucio/hellogowebserver
        ports:
        - containerPort: 8000